spring.application.name=mycode

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/erpdemo
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

#Gemini
## Gemini
#spring.ai.model.chat=google-genai
#spring.ai.google.genai.api-key=${GEMINI_API_KEY:}
#spring.ai.google.genai.chat.options.model=gemini-2.5-flash
#spring.ai.google.genai.chat.options.temperature=0


# Ollama Models
spring.ai.model.embedding=ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=phi4-mini:3.8b
spring.ai.ollama.chat.options.temperature=0
spring.ai.ollama.embedding.options.model=qwen3-embedding:0.6b

# PGVector Vector Store
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=hnsw
spring.ai.vectorstore.pgvector.distance-type=cosine_distance
spring.ai.vectorstore.pgvector.dimensions=1024

# Unstructured API RAG Extraction Config
unstructured.api.url=http://localhost:8000/general/v1/process
unstructured.api.strategy=hi_res
unstructured.enabled=true
unstructured.max-rows-per-chunk=10

# Multipart File Limits
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# JPA Hibernate Config
spring.jpa.properties.hibernate.id.db_structure_naming=legacy
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Security Secret
jwt.secret=${JWT_SECRET:}
